### ISSUE TITLE
HTML report

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [Subito-it/sbtuitestbrowser#1]
@tcamin Hi, I have found an excellent HTML reporting tool for xcuitest - https://github.com/TitouanVanBelle/XCUITestHTMLReport it would be really good to combine the video recording feature that is currently in sbtuitestbrowser, thanks for a great  tool 💯

**Comment by tcamin** [comment]
Looks like an awesome tool!

I'm however sticking with sbtuitestbrowser because I'm working on a distributed & parallel ui testing functionality which will require some custom implementation in the results browser to recombine everything in a single report.

**Comment by Ashraf-Ali-aa** [comment]
@tcamin if you looking for a CI to run the tests have a look at http://bbc.github.io/hive-ci/index.html it allows you to run on actual devices, also I have forked the project and added some more modifications and planning on adding much friendlier way of detecting simulators - https://github.com/hive-ci

**Comment by tcamin** [comment]
I just released un update that improves the way HTML is generated adding support for CSS. This should allow easier UI improvements in future. To some degree it looks nicer than before.

The new way you browse screenshots in the test detail is another great step forward in the tool.
