### ISSUE TITLE
Error when executing sbtuitestbrowser to generate report

### ISSUE THREAD

**Issue by adeemotu** [Subito-it/sbtuitestbrowser#6]
Hi , I was trying your tool . Successfully installed via brew, but when i execute sbtuitestbrowser [basepath], i get following error. Any tips how to sort it out.

dyld: Symbol not found: _$s15_ObjectiveCTypes01_A11CBridgeablePTl
  Referenced from: /usr/local/bin/sbtuitestbrowser
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib
 in /usr/local/bin/sbtuitestbrowser
Abort trap: 6

**Comment by tcamin** [comment]
I've updated the documentation:

_sbtuitestbrowser is written in Swift 5, so if you're on macOS Mojave 10.14.3 or earlier, you may need to install an optional Swift library package that can be downloaded from "More Downloads" for Apple Developers at https://developer.apple.com/download/more/_

**Comment by adeemotu** [comment]
👍 , Thanks @tcamin . Checked, working fine
